src/client/actions/invoice/delete.js
src/client/actions/notifications/index.js
src/client/components/CreateInvoice/SelectCustomerWizard.js
src/client/components/CreateInvoice/SelectCustomerWizardConstraints.js
src/client/components/InvoiceOverview/InvoiceDeleteModal.react.js
src/client/components/InvoiceOverview/SearchResult.react.js
src/client/components/InvoiceOverview/index.js
src/client/constants/modals.js
src/client/containers/InvoiceOverview.react.js
src/client/containers/Layout.react.js
src/client/containers/i18n/InvoiceOverview/de.js
src/client/containers/i18n/InvoiceOverview/en.js
src/client/reducers/index.js
src/client/reducers/modals.js
src/client/reducers/notification.js
src/server/db/migrations/invoice-migration/createInvoiceReceiptItem.js
src/server/db/models/InvoiceReceipt.js
src/server/db/models/InvoiceReceiptItem.js

Implemeted ability to delete invoice

---

src/client/components/InvoiceReceiptEditor/common/fetchers.js
src/client/components/InvoiceReceiptEditor/components/InvoiceEditor/index.js
src/client/components/InvoiceReceiptEditor/components/InvoiceOverview/index.js
src/server/acl.json
src/server/routes/index.js
src/server/routes/invoiceStatuses.js
src/server/stubData/invoiceStatuses.json

#24 Implemented. Added stub endpoint for invoice statuses. Reworked components in which invoice statuses were used.

#24 Added stub endpoint for invoice statuses.

---

src/client/components/InvoiceReceiptEditor/components/InvoiceEditor/InvoiceForm.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceEditor/InvoiceItemDeleteModal.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceEditor/InvoiceItemsGrid.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceEditor/InvoiceItemsPricePanel.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceEditor/SimpleEditor.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceEditor/SplitScreenEditor.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceEditor/index.js
src/client/components/InvoiceReceiptEditor/components/InvoiceItemEditor/InvoiceItemForm.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceItemEditor/index.js
src/client/components/InvoiceReceiptEditor/components/InvoiceOverview/InvoiceDeleteModal.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceOverview/InvoiceOverviewMarkup.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceOverview/SearchResult.react.js
src/client/components/InvoiceReceiptEditor/components/InvoiceOverview/index.js
src/client/components/common/form-components/FormsyDateInput.react.js
src/client/components/common/form-components/FormsyDateRange.react.js
src/client/components/common/form-components/FormsySelect.react.js
src/client/components/common/form-components/FormsyTextInput.react.js

#33 Implemented readOnly mode for invoice editor components.

#33 Added ability to view invoice editor in readonly mode. Small refactoring.

---

src/client/components/MyTasks/i18n/de.js
src/client/components/MyTasks/i18n/en.js
src/server/routes/approval/index.js
src/server/workflow/ApprovalSchema.json
src/server/workflow/ApprovalSchema.spec.js
src/server/workflow/actions.js
src/server/workflow/actions.spec.js
src/server/workflow/conditions.js
src/server/workflow/conditions.spec.js

Added the required changes to the workflow, added tests for conditions and actions.

#42 Implemented ability to calcel worfklow inspection & approval.

---

src/client/components/MyTasks/WideLayout.less
src/client/components/MyTasks/WideLayout.react.js
src/client/components/MyTasks/actions/ActionTabContent.react.js
src/client/components/MyTasks/actions/ActionsTabs.react.js
src/client/components/MyTasks/details/Details.react.js
src/client/components/MyTasks/i18n/de.js
src/client/components/MyTasks/i18n/en.js
src/client/components/MyTasks/index.js

#44 Implemented event-tabs.

---

src/client/routes/approval.js

#61 Updated criteria for MyTaskView data filtering.

---

src/client/components/MyTasks/layouts/EmptyLayout.react.js

#63 Fixed empty view translation.

---

src/client/components/MyTasks/data/fetchers.js

#59 Fixed issue under IE.

---

src/server/workflow/ApprovalSchema.json
src/server/workflow/ApprovalSchema.spec.js

#62 Updated. Commenting is not restricted by user role.

#62 Made commenting available on each approval step.

---

src/client/components/MyTasks/details/InvoiceAttachment/InvoiceAttachment.react.js
src/client/components/MyTasks/details/InvoiceDataDashboard/AttachmentDetails/AttachmentDetailsView.react.js
src/client/components/MyTasks/details/InvoiceDataDashboard/AttachmentDetails/index.js
src/client/components/MyTasks/details/InvoiceDataDashboard/InvoiceDataDashboard.react.js
src/client/components/MyTasks/i18n/en.js
src/server/routes/invoiceAttachment.js

#46 Fixes:
* Added ability to download invoice attachments from DataCard
* Increased supplier card  default height
* Fixed messages: 'Cancel Status', 'Comment Only' -> 'Cancel status', 'Comment only'

#46 Added possibility to download attachments plus minor fixes.

---

config/mocha-setup.js
package.json
src/client/components/MyTasks/helpers/UIHelpers.react.js
src/client/components/MyTasks/helpers/UIHelpers.react.spec.js
src/client/components/MyTasks/i18n/de.js
src/client/components/MyTasks/i18n/en.js
src/client/components/MyTasks/layouts/NarrowLayout.react.js
src/client/components/MyTasks/layouts/WideLayout.react.js
src/client/components/MyTasks/list/MyTasksList.react.js
src/client/components/MyTasks/sort-invoice/SortInvoice.less
src/client/components/MyTasks/sort-invoice/SortInvoice.react.js
src/client/routes/approval.js

#85 Added sorting.

---

src/client/components/MyTasks/constants/index.js
src/client/components/MyTasks/helpers/UIHelpers.react.js
src/client/components/MyTasks/list/TaskItem.less
src/client/components/MyTasks/list/TaskItem.react.js

#103 Modified invoice list item representation.

---

src/client/components/MyTasks/DataHandler.react.js
src/client/components/MyTasks/details/InvoiceDataDashboard/SupplierDetails/index.js
src/client/components/MyTasks/list/TaskItem.react.js
src/client/routes/approval.js

#97 Implemented.
Note: Customer and supplier data are loaded for each invoice regardless whether it has already been loaded for another invoice or not.

#97 Added supplier and customer loading for invoices.

---

src/client/components/MyTasks/helpers/UIHelpers.react.js
src/client/components/MyTasks/list/TaskItem.react.js

#103 Added decimal parts to invoice amount.

---

src/client/components/MyTasks/DataHandler.react.js
src/client/routes/approval.js

#86 Fixed not updated invoice.

---

src/client/components/MyTasks/list/MyTasksList.react.js

#98 Changed selection behavior when invoice is removed from list.

---

src/client/components/MyTasks/constants/index.js
src/client/components/MyTasks/helpers/UIHelpers.react.js
src/client/components/MyTasks/helpers/UIHelpers.react.spec.js
src/client/components/MyTasks/i18n/de.js
src/client/components/MyTasks/i18n/en.js
src/client/components/MyTasks/list/MyTasksList.react.js

#109 Added sorting by supplier name.

---

Dockerfile
package.json

#143 Moved production client bundle build into Dockerfile.

---

src/client/components/MyTasks/layouts/InvoiceLayout.less
src/client/components/MyTasks/layouts/InvoiceLayout.react.js
src/client/components/MyTasks/layouts/TaskLayoutHandler.react.js
src/client/routes/approval.js
src/server/routes/staticResources.js

-Add approval page to narrow layout
-Add posting to narrow layout

Add approval page to mobile view #107

---

src/client/components/MyTasks/layouts/NarrowLayout.less
src/client/components/MyTasks/layouts/TaskLayout.less
src/client/components/MyTasks/layouts/WideLayout.less
src/client/components/MyTasks/list/MyTasksList.less
src/client/containers/Layout.react.js

-MyTasks layout is broken on Safari browsers
-Bootstrap layouts prevent content from correctly using full view height

Fix broken MyTasks layout #155
